### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by zhorabay** [zhorabay/Catalog#26]
GitHub project link: https://github.com/zhorabay/Catalog/projects/1

Overall, 3 people in a team:
Team member #1 - @zhorabay 
Team member #2 - @Chimoneg27 
Team member #3 - @jubaer919 

Thank you for your review!

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job setting up the kanban board

## Required Changes ♻️
 - [ ] Team member 2 has significantly less workload than the rest of the team, please redistribute the work so that the difference between each team member is not more or less than 5 points in total.
 - [ ] In [the project requirements divided by group member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) the tasks are divided into bullet points, the idea is to create a separate card for each bullet point in this list.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
Hi Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>
## Highlights
- Changes effected ✔️ 
- Fair distribution of tasks ✔️
- Good use of Kanban board ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
